version: "3.8"

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
