"""remove status column

Revision ID: 27185d493247
Revises: fb9a9582561a
Create Date: 2025-10-10 21:20:30.204867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27185d493247'
down_revision: Union[str, Sequence[str], None] = 'fb9a9582561a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_status'), table_name='job_application')
    op.drop_column('job_application', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('status', postgresql.ENUM('SAVED', 'APPLIED', 'INTERVIEWED', 'OFFERED', 'REJECTED', 'ACCEPTED', name='status'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_job_application_status'), 'job_application', ['status'], unique=False)
    # ### end Alembic commands ###
