"""create job_interviews table

Revision ID: 3accdfb89ffc
Revises: f46f34b6d7c2
Create Date: 2025-09-01 19:33:59.518487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3accdfb89ffc'
down_revision: Union[str, Sequence[str], None] = 'f46f34b6d7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_application_id', sa.Uuid(), nullable=True),
    sa.Column('interview_type', sa.Enum('PHONE', 'VIDEO', 'ONSITE', name='jobinterviewtype'), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=False),
    sa.Column('interviewer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_interviews')
    # ### end Alembic commands ###
