"""add indexes to job_application table

Revision ID: a7ec0d9c83f9
Revises: c8bc3d4c6fbb
Create Date: 2025-09-06 10:03:30.035348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7ec0d9c83f9'
down_revision: Union[str, Sequence[str], None] = 'c8bc3d4c6fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_application_application_date'), 'job_application', ['application_date'], unique=False)
    op.create_index(op.f('ix_job_application_company_name'), 'job_application', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_application_deleted_at'), 'job_application', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_job_application_job_title'), 'job_application', ['job_title'], unique=False)
    op.create_index(op.f('ix_job_application_status'), 'job_application', ['status'], unique=False)
    op.create_index(op.f('ix_job_application_user_uid'), 'job_application', ['user_uid'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # create indexes
    op.execute("CREATE INDEX IF NOT EXISTS idx_company_trgm ON job_application USING gin (company_name gin_trgm_ops);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_title_trgm ON job_application USING gin (job_title gin_trgm_ops);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_user_uid'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_status'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_job_title'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_deleted_at'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_company_name'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_application_date'), table_name='job_application')
    op.execute("DROP INDEX IF EXISTS idx_company_trgm;")
    op.execute("DROP INDEX IF EXISTS idx_title_trgm;")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### end Alembic commands ###
