"""add created_at, updated_at, deleted_at in interview table

Revision ID: c8bc3d4c6fbb
Revises: 3accdfb89ffc
Create Date: 2025-09-03 08:18:13.010431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8bc3d4c6fbb'
down_revision: Union[str, Sequence[str], None] = '3accdfb89ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_interviews', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('job_interviews', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('job_interviews', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_interviews', 'deleted_at')
    op.drop_column('job_interviews', 'updated_at')
    op.drop_column('job_interviews', 'created_at')
    # ### end Alembic commands ###
