"""add status column to timelines table

Revision ID: ccbadd510b71
Revises: af46fcd157e8
Create Date: 2025-10-12 07:33:07.350279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccbadd510b71'
down_revision: Union[str, Sequence[str], None] = '27185d493247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_timeline', sa.Column('status', postgresql.ENUM('SAVED', 'APPLIED', 'INTERVIEWED', 'OFFERED', 'REJECTED', 'ACCEPTED', 'WITHDRAWN', name='status'), nullable=False))
    op.create_index(op.f('ix_job_timeline_status'), 'job_timeline', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_timeline_status'), table_name='job_timeline')
    op.drop_column('job_timeline', 'status')
    # ### end Alembic commands ###
