"""relate users to job_application

Revision ID: f46f34b6d7c2
Revises: c55bdfd9fdd5
Create Date: 2025-08-28 22:20:32.746121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f46f34b6d7c2'
down_revision: Union[str, Sequence[str], None] = 'c55bdfd9fdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'job_application', 'users', ['user_uid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_application', type_='foreignkey')
    op.drop_column('job_application', 'user_uid')
    # ### end Alembic commands ###
