"""create job timeline table

Revision ID: fb9a9582561a
Revises: a7ec0d9c83f9
Create Date: 2025-10-01 20:54:09.704433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb9a9582561a'
down_revision: Union[str, Sequence[str], None] = 'a7ec0d9c83f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_application_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', postgresql.ENUM('SAVED', 'APPLIED', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'OFFER_RECEIVED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'REJECTED', 'WITHDRAWN', name='job_application_event'), nullable=False),
    sa.Column('event_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_timeline_deleted_at'), 'job_timeline', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_job_timeline_event_type'), 'job_timeline', ['event_type'], unique=False)
    op.drop_index(op.f('idx_company_trgm'), table_name='job_application', postgresql_ops={'company_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_title_trgm'), table_name='job_application', postgresql_ops={'job_title': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_title_trgm'), 'job_application', ['job_title'], unique=False, postgresql_ops={'job_title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_company_trgm'), 'job_application', ['company_name'], unique=False, postgresql_ops={'company_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_job_timeline_event_type'), table_name='job_timeline')
    op.drop_index(op.f('ix_job_timeline_deleted_at'), table_name='job_timeline')
    op.drop_table('job_timeline')
    # ### end Alembic commands ###
